### DISCUSSION TITLE
Admin read only folder on Docker

### DISCUSSION THREAD

**Discussion by DiR3KT** [9001/copyparty#99] [Q&A] [answered]
Hello!
I'm really new to docker and everything, and really liked your project!
I ran the docker compose, everything is fine!

My goal is to have guest users have access to the root with read/write
And have a secret folder only for admins, let's say the user "test" for now.
So I modified the copyparty.conf next to my docker compose according to your example, but I don't know how to specify authorization for specific user on a specific folder:

```
[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # enable multimedia indexing
  ansi   # enable colors in log messages

  # q, lo: /cfg/log/%Y-%m%d.log   # log to file instead of docker

  # p: 3939          # listen on another port
  # ipa: 10.89.      # only allow connections from 10.89.*
  # df: 16           # stop accepting uploads if less than 16 GB free disk space
  # ver              # show copyparty version in the controlpanel
  # grid             # show thumbnails/grid-view by default
  # theme: 2         # monokai
  # name: datasaver  # change the server-name that's displayed in the browser
  # stats, nos-dup   # enable the prometheus endpoint, but disable the dupes counter (too slow)
  # no-robots, force-js  # make it harder for search engines to read your server


[accounts]
  test: test  # username: password


[/]            # create a volume at "/" (the webroot), which will
  /w           # share /w (the docker data volume)
  accs:
    rw: *      # everyone gets read-write access, but
    rwmda: test  # the user "ed" gets read-write-move-delete-admin
  /w/test
  accs:
    rwmda: test
```

I get this error when restarting the container:
**error @ line 37, included from /z/initcfg**

Do you know how I can specify certain rights for a specific subfolder of the share?

Thanks a lot!

**Comment by 9001** [comment, marked as answer]
nice, you *almost* got it right :-)

I think this should work:

```yaml
[/]              # create a volume at "/" (the webroot), which will
  /w             # share /w (the docker data volume)
  accs:
    rw: *        # everyone gets read-write access, but
    rwmda: test  # the user "test" gets read-write-move-delete-admin

[/test]      # and then create another volume, accessible at the URL "/test",
  /w/test    # ...and hook it up to this folder on your server's filesystem
  accs:
    rwmda: test
```

and, just to explain why it works like this -- it's because sometimes you want to do more crazy stuff... like this for example:

```yaml
[/]
  /w/public
  accs:
    r: *

[/admin]
  /w/admin
  accs:
    rwmda: test

[/music]
  /w/admin/shared/music
  accs:
    r: *
```

this would create 3 URLs:
* `/` and `/music` are accessible for everyone
* `/admin` is admin-only

and here's the cool part... these two URLs would then send you into the same folder on the server:
* https://www.example.com/music/aiobahn/
* https://www.example.com/admin/shared/music/aiobahn

thanks for giving copyparty a try! hope you enjoy your stay :>
