### ISSUE TITLE
Cannot move/rename file/directory whereas it should

### ISSUE THREAD

**Issue by hugo-akaora** [9001/copyparty#100]
**Describe the bug**
I cannot move or rename a file nor directory where as it should be possible regarding my volflags

**To Reproduce**
Add in your config file add: 
```
[/podcasts]
  /files2/Music
  accs:
    r: *
    rwmda: hugo
```

Connect as "hugo".

In logs you should see:
```
"/podcasts"  /files2/Music
|    read:  everybody
|   write:  hugo
|    move:  hugo
|  delete:  hugo
|    dots:  everybody
|     get:  --none--
|   upGet:  --none--
|    html:  --none--
|  uadmin:  hugo
```

As expected.

Upload an editable file to the directory, eg ".prologue.html". File seems to be named `_.prologue.html` after upload. Open the file, on your keyboard press [F2], you should see a popup:

![image](https://github.com/user-attachments/assets/49681612-f21c-4dc8-8ae1-9d66d674297b)

**Expected behavior**
File should be editable

**Server details**
if the issue is possibly on the server-side, then mention some of the following:
* server OS / version: Debian 12 / "ac" Docker container
* python version: v3.12.6
* copyparty arguments: 
* complete Dockerfile:
```yaml
services:
  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    user: "1000:1000"
    volumes:
      - ${DOCKER_VOLUME_STORAGE_PATH}/copyparty/cfg:/cfg
      - ${DOCKER_VOLUME_STORAGE_PATH}/copyparty/files:/files
      - ${DOCKER_VOLUME_STORAGE_PATH}/copyparty/files2:/files2
    command: [
      # run docker run --rm -it copyparty/ac --help for argument explanation 
      # tls (will be managed via traefik)
      "--no-crt",
      "--http-only",
      # network (adapt to traefik)
      "--xff-src=lan",
      # enable file indexing and filesystem scanning
      "-e2dsa",
      # enable multimedia indexing
      "-e2ts",
      # enable colors in log messages
      "--ansi",
      # password
      # "--ah-alg=argon2",
      # zeroconf
      "-z",
      # opt-outs (hide some unnecessary information)
      "-nid",
      "-nth",
      "-nid",
      "-nb",
      # do not write uploader IPs into the database
      "--no-db-ip",
      # disable race-the-beam (lockstep download of files which are currently being uploaded) (volflag=nopipe)
      "--no-pipe",
      # stop accepting uploads if less than 16 GB free disk space
      "--df=10",
      # monokai
      "--theme=3",
      # change the server-name that's displayed in the browser
      "--name=iglou-${IGLOU_NAME}",
      # config files
      "-c /cfg/accounts.conf /cfg/shares.conf",
      # enable the ?dots url parameter / client option which allows clients to see dotfiles / hidden files
      "-ed"
    ]
    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.services.copyparty.loadbalancer.server.port: 3923
      traefik.http.routers.copyparty.rule: Host(`copyparty.${BASE_DOMAIN}`)
      traefik.http.routers.copyparty.entrypoints: web,websecure
      traefik.http.routers.copyparty.tls: true
    networks:
      - proxy

networks:
  proxy:
    external: true
```
* copyparty v1.15.3 "fill the drives" (2024-09-16)

* filesystem (`lsblk -f` on linux): ext4

Thank you!
