### ISSUE TITLE
WebDav Permissions Aren't Working Correctly

### ISSUE THREAD

**Issue by WilsontheWolf** [9001/copyparty#136]
### Describe the bug
My WebDav connection seems to be using the default user permissions despite me being logged in.

WebDav Client: KDE Dolphin
I set `dav-auth` to force dolphin to prompt for a login. However I cannot delete files 

![Image](https://github.com/user-attachments/assets/cc57ac00-0271-40e6-a855-941857a5c77d)

and editing files causes a new file with a suffix on it instead of replacing it.

![Image](https://github.com/user-attachments/assets/5cf04e78-4cd9-461f-9010-0575ea84102c)

The web client does confirm I have the perms and I can correctly delete files there

![Image](https://github.com/user-attachments/assets/5e140c6f-6b1d-4171-9a85-cd5f74b9d277)

### Server details (if you are using docker/podman)
remove the ones that are not relevant:
* **server OS / version:** Debian 12 (proxmox VM)
* **how you're running copyparty:** docker 
* **docker image:** copyparty/ac:latest x86_64
* **copyparty arguments and/or config-file:** 
```yaml
# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:


[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # enable multimedia indexing
  ansi   # enable colors in log messages

  # q, lo: /cfg/log/%Y-%m%d.log   # log to file instead of docker

  # p: 3939          # listen on another port
  # ipa: 10.89.      # only allow connections from 10.89.*
  # df: 16           # stop accepting uploads if less than 16 GB free disk space
  # ver              # show copyparty version in the controlpanel
  # grid             # show thumbnails/grid-view by default
  # theme: 2         # monokai
  name: scratch  # change the server-name that's displayed in the browser
  no-robots
  xff-src: lan
  dav-auth


[accounts]
  shorty: pass

[/]            # create a volume at "/" (the webroot), which will
  /w           # share /w (the docker data volume)
  accs:
    rw: *      # everyone gets read-write access, but
    A: shorty
```

`docker-compose.yml`

```yml
version: '3'
services:

  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    restart: unless-stopped
    ports:
      - 3923:3923
    volumes:
      - ./:/cfg:z
      - /root/public:/w:z

    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s
```

Not sure if its jhelpful but this is the logs spit out when uploading a file

```
copyparty  | 08:24:59.586 142.66.76.34 55726    PFIND / @*
copyparty  | 08:24:59.586 142.66.76.34 55726    http401: authenticate, '/'
copyparty  | 08:24:59.616 142.66.76.34 55736    PFIND /lculq0CdNUpNWTQd.mp4 @*
copyparty  | 08:24:59.616 142.66.76.34 55736    http401: authenticate, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:24:59.677 142.66.76.34 55738    PFIND / @shorty
copyparty  | 08:24:59.702 142.66.76.34 55738    PFIND / @*
copyparty  | 08:24:59.702 142.66.76.34 55738    http401: authenticate, '/'
copyparty  | 08:24:59.703 142.66.76.34 55740    PFIND /lculq0CdNUpNWTQd.mp4 @shorty
copyparty  | 08:24:59.732 142.66.76.34 55740    PFIND / @*
copyparty  | 08:24:59.732 142.66.76.34 55740    http401: authenticate, '/'
copyparty  | 08:24:59.733 142.66.76.34 34972    PFIND /lculq0CdNUpNWTQd.mp4 @*
copyparty  | 08:24:59.733 142.66.76.34 34972    http401: authenticate, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:24:59.798 142.66.76.34 34988    PFIND / @shorty
copyparty  | 08:24:59.826 142.66.76.34 34988    PFIND / @shorty
copyparty  | 08:24:59.827 142.66.76.34 34994    PFIND /lculq0CdNUpNWTQd.mp4 @shorty
copyparty  | 08:25:06.315 142.66.76.34 34994    PFIND / @*
copyparty  | 08:25:06.316 142.66.76.34 34994    http401: authenticate, '/'
copyparty  | 08:25:06.411 142.66.76.34 34988    PFIND / @shorty
copyparty  | 08:25:21.966 127.0.0.1 44514       HEAD /?reset @*
copyparty  | 08:26:06.379 142.66.76.34 34988    PFIND / @*
copyparty  | 08:26:06.379 142.66.76.34 34988    http401: authenticate, '/'
copyparty  | 08:26:06.469 142.66.76.34 36992    PFIND / @shorty
copyparty  | 08:26:22.022 127.0.0.1 45570       HEAD /?reset @*
copyparty  | 08:27:06.285 142.66.76.34 36992    PFIND / @*
copyparty  | 08:27:06.285 142.66.76.34 36992    http401: authenticate, '/'
copyparty  | 08:27:06.372 142.66.76.34 54262    PFIND / @shorty
copyparty  | 08:27:07.689 142.66.76.34 54262    GET  / @shorty
copyparty  | 08:27:07.881 142.66.76.34 54262    GET  /?tree= @shorty
copyparty  | 08:27:13.744 142.66.76.34 54262    POST /lculq0CdNUpNWTQd.mp4?delete @shorty
copyparty  | 08:27:13.744 up2k                  rm 'lculq0CdNUpNWTQd.mp4'
copyparty  |   '/w/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:13.744 up2k                  forgetting 'lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:13.744 up2k                  found x-QD5ZdaN2I32yjC35PdsnOrrFs6D_jmrFjYDnlVVUrV in db
copyparty  | 08:27:13.746 142.66.76.34 54262    deleted 1 files (and 0/0 folders)
copyparty  | 08:27:13.787 142.66.76.34 54262    GET  /?tree= @shorty
copyparty  | 08:27:13.788 142.66.76.34 54262    GET  /?ls @shorty
copyparty  | 08:27:19.030 142.66.76.34 54262    PFIND /lculq0CdNUpNWTQd.mp4 @*
copyparty  | 08:27:19.030 142.66.76.34 54262    http401: authenticate, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:19.034 142.66.76.34 42306    PFIND /lculq0CdNUpNWTQd.mp4 @*
copyparty  | 08:27:19.034 142.66.76.34 42306    http401: authenticate, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:19.125 142.66.76.34 42312    PFIND /lculq0CdNUpNWTQd.mp4 @shorty
copyparty  | 08:27:19.125 142.66.76.34 42312    http404: Not Found, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:19.137 142.66.76.34 42318    PFIND /lculq0CdNUpNWTQd.mp4 @shorty
copyparty  | 08:27:19.137 142.66.76.34 42318    http404: Not Found, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:19.446 142.66.76.34 42322    PFIND /lculq0CdNUpNWTQd.mp4 @*
copyparty  | 08:27:19.446 142.66.76.34 42322    http401: authenticate, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:19.536 142.66.76.34 42326    PFIND /lculq0CdNUpNWTQd.mp4 @shorty
copyparty  | 08:27:19.537 142.66.76.34 42326    http404: Not Found, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:19.718 142.66.76.34 42330    PFIND / @*
copyparty  | 08:27:19.718 142.66.76.34 42330    http401: authenticate, '/'
copyparty  | 08:27:19.722 142.66.76.34 57310    PFIND / @*
copyparty  | 08:27:19.722 142.66.76.34 57310    http401: authenticate, '/'
copyparty  | 08:27:19.806 142.66.76.34 57320    PFIND / @shorty
copyparty  | 08:27:19.813 142.66.76.34 57320    PFIND / @shorty
copyparty  | 08:27:20.053 142.66.76.34 57320    PFIND / @*
copyparty  | 08:27:20.053 142.66.76.34 57320    http401: authenticate, '/'
copyparty  | 08:27:20.142 142.66.76.34 57336    PFIND / @shorty
copyparty  | 08:27:20.326 142.66.76.34 57336    PFIND / @*
copyparty  | 08:27:20.327 142.66.76.34 57336    http401: authenticate, '/'
copyparty  | 08:27:20.416 142.66.76.34 57338    PFIND / @shorty
copyparty  | 08:27:22.095 127.0.0.1 45620       HEAD /?reset @*
copyparty  | 08:27:24.226 142.66.76.34 57338    PFIND / @*
copyparty  | 08:27:24.226 142.66.76.34 57338    http401: authenticate, '/'
copyparty  | 08:27:24.319 142.66.76.34 57346    PFIND / @shorty
copyparty  | 08:27:24.366 142.66.76.34 57346    PFIND / @*
copyparty  | 08:27:24.366 142.66.76.34 57346    http401: authenticate, '/'
copyparty  | 08:27:24.367 142.66.76.34 57350    PFIND / @*
copyparty  | 08:27:24.367 142.66.76.34 57350    http401: authenticate, '/'
copyparty  | 08:27:24.368 142.66.76.34 57366    PFIND / @*
copyparty  | 08:27:24.368 142.66.76.34 57366    http401: authenticate, '/'
copyparty  | 08:27:24.392 142.66.76.34 57374    PFIND / @*
copyparty  | 08:27:24.392 142.66.76.34 57374    http401: authenticate, '/'
copyparty  | 08:27:24.462 142.66.76.34 57384    PFIND / @shorty
copyparty  | 08:27:24.464 142.66.76.34 57384    PFIND / @shorty
copyparty  | 08:27:24.465 142.66.76.34 57396    PFIND / @shorty
copyparty  | 08:27:24.483 142.66.76.34 57408    PFIND / @shorty
copyparty  | 08:27:24.662 142.66.76.34 57408    PFIND / @*
copyparty  | 08:27:24.662 142.66.76.34 57408    http401: authenticate, '/'
copyparty  | 08:27:24.754 142.66.76.34 57396    PFIND / @shorty
copyparty  | 08:27:24.766 142.66.76.34 57396    PFIND / @*
copyparty  | 08:27:24.766 142.66.76.34 57396    http401: authenticate, '/'
copyparty  | 08:27:24.864 142.66.76.34 57384    PFIND / @shorty
copyparty  | 08:27:25.179 142.66.76.34 57384    PFIND / @*
copyparty  | 08:27:25.179 142.66.76.34 57384    http401: authenticate, '/'
copyparty  | 08:27:25.271 142.66.76.34 57422    PFIND / @shorty
copyparty  | 08:27:25.502 142.66.76.34 57422    PFIND /lculq0CdNUpNWTQd.mp4 @*
copyparty  | 08:27:25.502 142.66.76.34 57422    http401: authenticate, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:25.594 142.66.76.34 57438    PFIND /lculq0CdNUpNWTQd.mp4 @shorty
copyparty  | 08:27:25.594 142.66.76.34 57438    http404: Not Found, '/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:25.817 142.66.76.34 57450    PUT  /lculq0CdNUpNWTQd.mp4 @*
copyparty  | 08:27:26.255 142.66.76.34 57450    5.02M 11.5M/s 5.02M 11.4M/s n0 wrote 5273587/5273587 bytes to '/w/lculq0CdNUpNWTQd.mp4'  # LdeApwgA1zflxgsVLFXzq2NnEsqC
copyparty  | 08:27:26.255 up2k                  hashing '/w/lculq0CdNUpNWTQd.mp4'
copyparty  | 08:27:26.334 up2k                  tagged '/w/lculq0CdNUpNWTQd.mp4' (14+0)
copyparty  | 08:27:26.498 142.66.76.34 57450    PFIND / @*
copyparty  | 08:27:26.498 142.66.76.34 57450    http401: authenticate, '/'
copyparty  | 08:27:26.507 142.66.76.34 57466    PFIND / @*
copyparty  | 08:27:26.507 142.66.76.34 57466    http401: authenticate, '/'
copyparty  | 08:27:26.543 142.66.76.34 57482    PFIND /lculq0CdNUpNWTQd.mp4 @*
copyparty  | 08:27:26.543 142.66.76.34 57482    http401: authenticate, '/lculq0CdNUpNWTQd.mp4'

```
nothing is logged if I try saving over an existing file
