### ISSUE TITLE
Request for Additional Information Regarding Thumbnail Configuration

### ISSUE THREAD

**Issue by armouredking** [9001/copyparty#170]
Currently doing a file move so my CP instance is in the midst of a several hour scan operation and stressing the CPU so don't have anything I can test with atm.

With regards to the functionality discussed [here](https://github.com/9001/copyparty?tab=readme-ov-file#thumbnails), is `ext-th` similar to `th-covers` where you can specify multiple mime-types in a comma separated list, or does `ext-th` need to be an array / multi-line entry?

i.e. would it be something like:
```
ext-th: exe=/path/to/exe.icon md=/path/to/md.icon ...
```
OR
```
ext-th: exe=/path/to/exe.icon,md=/path/to/md.icon,...
```
OR
```
ext-th: exe=/path/to/exe.icon
ext-th: md=/path/to/md.icon
...
```

Additional question: what is an acceptable thumbnail file? Because a lot of downloadable thumbnail packs (like the stuff you can get for OS - particularly Linux - themes) use svgs, would that be allowed?

**Comment by 9001** [comment]
thanks for the heads-up, the readme should be better now 👍 

I'm suspecting that `.icon` is the same as `.ico`, and in that case I'd recommend renaming them to `.ico` since that's the more common extension (greater chance of mapping to the correct mimetype).

I've closed the issue but go ahead and ask if there's anything else :>

**Comment by armouredking** [comment]
So I can't make this work. I don't _see_ any errors in the logs (but every time I restart it's scanning more files, even though it finished... not sure why, I'm guessing it didn't actually do the full drive even though it said it did, is there a timeout on scan?)

Relevant Config:
```
[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # enable multimedia indexing
  ansi   # enable colors in log messages
  re-maxage: 86400    # rescan every day
  hist: /cfg/hists/  # pull all copyparty thumbs into a single location
  dbpath: /cfg/dbs/  # pull all copyparty sqlite dbs into a single location
  xff-hdr: x-forwarded-for
  xff-src: 172.0.0.0/8
  ver              # show copyparty version in the controlpanel
  # Create our own little MIME setup
  ext-th: 7z=/.icons/ark.svg
  ext-th: rar=/.icons/ark.svg
  ext-th: zip=/.icons/ark.svg
  ext-th: tar=/.icons/ark.svg
  ext-th: bz=/.icons/ark.svg
  ext-th: gz=/.icons/ark.svg
  ext-th: doc=/.icons/word.svg
  ext-th: docx=/.icons/word.svg
  ext-th: epub=/.icons/epub.svg
  ext-th: exe=/.icons/exe.svg
  ext-th: html=/.icons/html.svg
  ext-th: java=/.icons/java.svg
  ext-th: json=/.icons/json.svg
  ext-th: md=/.icons/md.svg
  ext-th: ods=/.icons/excel.svg
  ext-th: pdf=/.icons/pdf.svg
  ext-th: php=/.icons/php.svg
  ext-th: py=/.icons/python.svg
  ext-th: sh=/.icons/shell.svg
  ext-th: sql=/.icons/sql.svg
  ext-th: ttf=/.icons/ttf.svg
  ext-th: txt=/.icons/txt.svg
  ext-th: xls=/.icons/excel.svg
  ext-th: xlsx=/.icons/excel.svg
  ext-th: xml=/.icons/xml.svg
  ext-th: yaml=/.icons/yaml.svg
  ext-th: zim=/.icons/zim.svg

[/]
  /tank
  accs:
    rwmd.: *
```

Stripped the logins out, but otherwise, this is all there is. The folder ".icons" is located under [/] (/tank) on the docker volume, and has the correct permissions (I can see the files by allowing view of dots, or just typing in the address)

**Comment by armouredking** [comment]
Okay, so interesting bit, it won't do it to all of them, only the scanned files. If I go hunting, I can find folders that have partials. Here's an example:
![Image](https://github.com/user-attachments/assets/b60a47cd-f13a-466d-aa8c-d00e5d1c8a35)

The tail of the log shows that it's 'finished' with it's scan after startup:
```
00:38:28.918 up2k                  commit 0 new files; 4 updates
00:38:28.966 up2k                  uploads are now possible
00:38:28.966 up2k                  online (reading tags) [/tank]
00:38:28.966 up2k                  online (reading tags) [/wiki]
00:38:28.968 up2k                  2 volumes in 483.47 sec
00:38:28.969 up2k                  mtp finished in 0.00 sec (0:00)
------------------------
```

So, a few new questions:

1) How to force it to go and not stop until I say so, or it's done done?
2) Why does using the SVGs result in the ugliness here? Specifically with file names? As SVGs, they should resize to fill the 'preview' box no? Not sure what's happening here.

![Image](https://github.com/user-attachments/assets/d27a633f-7de4-4625-8c77-7eeb228a4591)
![Image](https://github.com/user-attachments/assets/a0167c31-8c7e-46ef-b581-916f21022728)

Shouldn't we have the full box? Because otherwise you get a mess.

---

Edit: Random other note, again because I'm looking at logs too much:

```
01:21:30.420 192.168.139.54 50338  GET  /?ls&rtt=27 @*
OPYTHAT
01:22:20.741 hsrv                  ok bye
01:22:20.741 tcpsrv                ok bye
01:22:20.741 up2k                  writing snapshot
01:22:20.793 root                  nailed it
```

Looks like the goodbye COPYTHAT is missing its leading C. I thought maybe it was getting cutoff in my logs but I've seen it a few times.

**Comment by 9001** [comment]
gotcha -- I think I have explanations for all of these,

> every time I restart it's scanning more files, even though it finished

on startup, it does a quick scanthrough of all the folders, looking for new files (or deleted files). If necessary, it does this by exactly comparing the database to the contents on the disk, but there is also an optimization (default-enabled) which instead compares a hash of the contents of each directory, instead of individual files. This optimization saves quite a bit of time -- but, as a safety measure, if copyparty is terminated mid-startup, it will disengage that optimization for the next startup only. So it should start faster the next time if you let it finish scanning before terminating it.

as for the thumbnails not applying to all files, this is primarily due to copyparty trying to identify file extensions such as "tar.gz". Specifically, it thinks that "export.json" is the file extension, and not just "json". Currently the limit is two words, each of 7 characters or less, applies both [serverside](https://github.com/9001/copyparty/blob/fa5845ff5feb6995a694615cfddcc9925d679565/copyparty/httpcli.py#L4640) and [clientside](https://github.com/9001/copyparty/blob/fa5845ff5feb6995a694615cfddcc9925d679565/copyparty/web/browser.js#L6467), so the file extension of `foo.bar.qwertyu.asdfghj` would be assumed to be `qwertyu.asdfghj`.

question 2, the text getting messed up and not filling the whole box, is due to two reasons -- the svg has a native size in its metadata, so the browser renders it at that size, instead of filling as much space as possible (which the raster images generally do, having a resolution larger than its shrunk-for-presentation size). Copyparty doesn't currently have any logic for detecting and mitigating this. This leaves a lot of extra space, making the next issue more obvious:

The text getting truncated to 3 lines is working as intended, and that's to prevent excessively long filenames making the entire row taller. The max number of lines to allow is the "chop:" option in the toolbar. It's not smart enough to realize that there's enough space to include some more lines, and maybe that's possible to do something about -- I'm not entirely sure yet. And the thing about seeing a tiny bit of the 4th line at the bottom, that's probably some jank in my line height calculation, I'll look into that.

I can think of two workarounds; one is to convert all the svg files into png's at a higher resolution (512 or so), or alternatively you could force all images loaded from the "/.icons" folder to fill the available space with the following custom css:

```css
#ggrid img[src^="/.icons/"] {
  height: calc(var(--grid-sz)/1.25);
}
```

finally and most importantly...

> Looks like the goodbye COPYTHAT is missing its leading C

hehe, so the reason that's there is because the terminal itself prints the ^C when you hit ctrl-c, shifting all the text on the next line by two characters... so that's why copyparty prints "OPYTHAT\n" to put the ^C to good use 😁 so the ^C part doesn't make it into the logs since it's not something that copyparty is emitting, but I think we can accept that :>
