### ISSUE TITLE
Got myself banned from my own server because private files showed up in a search

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#61]
I have a 'private' volume with permissions only to myself:
```yaml
accs:
     rwmda: gremious
   flags:
     fk: 8
     fka,
```
(I now notice that fk is useless there but that's what it was)

1. Opened new Firefox private window
2. Searched "a" to test #60
3. See files from said private volumes in the search, but they had no thumbnails
4. Get concerned, click file
5. "thank you for playing"
6. ok
