### ISSUE TITLE
Cutting and pasting a symlink loses it (does not relink?)

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#65]
**Describe the bug**
If you cut and paste an existing link copy of a file into a different folder, it disappears in copyparty.

**To Reproduce**
I have the following config:
```yaml
[global]
theme: 2
ftp: 3921
ftps: 3990
ftp-pr: 12000-13000
# Use hashed passwords
ah-alg: argon2
# Thumbnail view on by default
grid
# Enable general file indexing
# Maybe it's called "e2d..." because it uses an 'up2k' tree for the database...
e2dsa
# Enable metadata and tag indexing (ffprobe)
e2ts
# Full-sized image thumbnails
th-no-crop
# Don't crawl my website please google
force-js
no-robots
# Don't create symlinks to deduplicate, make copies of every file
# no-dedup
# Allow cross-volume symlinks for deduplication
xlink

[/protected]
/snip/protected
accs:
  rwmda: gremious
  G: *
flags:
  fk: 8
  fka,
```

1. make folder `/protected/one`
2. make folder `/protected/two`
3. make folder `/protected/two/three`
4. Upload [a new image you don't have](https://robson.plus/white-noise-image-generator/) to `protected/one`
5. Upload the same image to `protected/two`
(so far everything is OK)
6. Select said image and cut, then paste it into `/protected/two/three`
7. Refresh

Notice image is not there in ether `/protected/two/three` or `/protected/two`

copyparty logs say:

```
Dec 08 13:14:46 hostname copyparty[1575637]: 13:14:46.399 scandir
[s] FileNotFoundError(2, 'No such file or directory') @ /snip/protected/two/three/noise.png
```

The link is still there on the filesystem ([eza](https://github.com/eza-community/eza) is just a fancy `ls`):

```
gremious@hostname ~> eza -l snip/protected/two/
drwxr-xr-x - gremious  8 Dec 13:11 three
gremious@hostname ~> eza -l snip/protected/two/three/
lrwxrwxrwx - gremious  8 Dec 13:10 noise.png -> ../one/noise.png
```

However, I think that should be `../../one/noise.png` now and not `../one/noise.png`?

**Server details**
* server OS / version: Debian bullseye
* python version: Python 3.9.2
* filesystem (`lsblk -f` on linux): btrfs
