### ISSUE TITLE
add configuration for fonts that copyparty uses

### ISSUE THREAD

**Issue by thaddeuskkr** [9001/copyparty#74]
it'd be nice to be able to use custom fonts on copyparty by adding something to the configuration, allowing for a import url or a font file? i'm actually not that sure how many fonts copyparty uses, but it looks like two?

maybe like
```yaml
[global]
font: 
font-code: 
```

**Comment by 9001** [comment]
Good idea :+1: 

I've pushed new docker images with the necessary changes, and tried to document how to actually change the fonts here: https://github.com/9001/copyparty/tree/hovudstraum/docs/rice

Closed the issue since I think it should be good to go, but please keep commenting if anything's unclear or busted :>

**Comment by thaddeuskkr** [comment]
I got the font change to work, but it doesn't seem to change the font of the markdown preview - for normal text at least
![image](https://github.com/9001/copyparty/assets/49682825/88ab09cf-8765-4408-8fd8-d0850340f2dd)

My CSS file is as follows:
```css
@import url("https://www.tkkr.dev/fonts/stylesheet.css");
@import url("https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,300..900;1,300..900&display=swap");

:root {
	--font-main: 'Figtree';
	--font-serif: var(--font-main);
	--font-mono: 'Brass Mono';
}
```

**Comment by 9001** [comment]
oh right, yep the markdown preview is sandboxed so it doesn't see the customizations yet -- I'll fix that tonight 👍

**Comment by 9001** [comment]
new docker images are up!

and just realized the buildscript nuked and replaced the `1.10.2` images too, not just the `latest` tag... oh well heh

**Comment by thaddeuskkr** [comment]
alrite, thanks, markdown preview now has the applied fonts

![image](https://github.com/9001/copyparty/assets/49682825/d2f9098f-390e-4bd0-b74c-d8650aab1cb8)
text in inputs and buttons don't apply though :>

sorry for the trouble 😆

**Comment by thaddeuskkr** [comment]
one more slightly unrelated thing, is the fancy markdown editor supposed to use the code font in the editor window? or is this normal behaviour for it not to

![image](https://github.com/9001/copyparty/assets/49682825/5a73775a-584e-42a6-aa04-4f4d13e18c18)

**Comment by 9001** [comment]
> text in inputs and buttons don't apply though :>

right yup, inputs don't inherit fonts by default (lol css)

I think the best fix for this is to override it in your css if you want to, since that way you can specify exactly what you want where --

```css
input[type=text], input[type=submit], input[type=button] { font-family: var(--font-main) }
```

I'm expecting the regular markdown editor to entirely fall apart if there's a mismatch between the fonts in two of its elements (the `<textarea id="mt">` and the `<div id="mtr">`), so changing the font of `textarea`s is probably a bad idea heh 

> is the fancy markdown editor supposed to use the code font in the editor window?

nope! or rather, that's how [EasyMDE](https://github.com/Ionaru/easy-markdown-editor) works out of the box, so I'm guessing it's intended behavior to use the sans-serif font everywhere. You can override that if you'd like, but I'm suspecting this could have unintended side-effects (word-wrapping or scroll-sync getting weird):

```css
.EasyMDEContainer .CodeMirror { font-family: var(--font-mono) }
```

I'll add all this to the rice readme, thx :+1:
